[build]
	command = "npm run build"
	publish = "build"
	functions = "functions"

[dev]
	functions = "functions"

# clean up our api urls
[[redirects]]
	from = "/api/*" # the path we want to redirect
  to = "/.netlify/functions/api/:splat" # the url or path we want to redirect to
  status = 200