# root configuration

[build]
	publish = "client/build"
	functions = "functions"
	command = "npm run build"
	node_bundler = "esbuild"

[dev]
	publish = "client"
	functions = "functions"
	command = "npm run start"
	node_bundler = "esbuild"

# users api redirects
[[redirects]]
	from = "/*"
	to = "/.netlify/functions/api/:splat"
	status = 200