# root configuration

[dev]
	publish = "client"
	function = "functions"

[functions]
	# functions configuration (https://docs.netlify.com/configure-builds/file-based-configuration/#functions)
  directory = "functions"

# users api redirects
[[redirects]]
	from = "/*"
	to = "/.netlify/functions/api/:splat"
	status = 200