[build]
	base = "client"
	command = "npm run build"
	publish = "build"

[dev]
	base = "client"
	command = "npm run start"

[functions]
  # Sets a custom directory for Netlify Functions
  directory = "functions"

[[redirects]]
	from = "/*"
	to = "/.netlify/functions/api/:splat"
	status = 200